version: "3"
services:
  jupyterlab:
    build:
      context: ../
      dockerfile: ./JupyterLab/Dockerfile 
      args:
    container_name: datascience
    image: isischameleon/usyd-data-science:debugger
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - "8890:8888"
    volumes:
      - notebooks:/home/joyvan/notebooks
      - data:/home/jovyan/data
    command: start.sh jupyter lab
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #      - capabilities: [gpu]