version: "3.3"
services: # all services are automatically added to a default created network for all services in the compose file
  jupyterlab:
    image: 'isischameleon/usyd-data-science:debugger'
    volumes:
      - notebooks:/home/joyvan/notebooks
      - data:/home/jovyan/data
    container_name: jupy
    build:
      context: ./
      dockerfile: ./Dockerfile 
    ports:
      - "8890:8888"

    command: start.sh jupyter lab
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #      - capabilities: [gpu]
volumes:
  data: 
  notebooks:
