FROM mcr.microsoft.com/dotnet/sdk as dotnetcore

RUN mkdir "/dotnet"

WORKDIR /dotnet

#  docker build --rm -t isischameleon/dotnet .
#  docker run -it --name dotnetc -v dotnet:/dotnet isischameleon/dotnet
